services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
  soc_v3:
    build:
      context: .
      dockerfile: docker/Dockerfile.cloud
    command: uvicorn v3.cloud.soc_api:app --host 0.0.0.0 --port 8000
    ports:
      - "9000:8000"
    volumes:
      - .:/app
  soc_v4:
    build:
      context: .
      dockerfile: docker/Dockerfile.cloud
    command: uvicorn v4.cloud.soc_api_v4:app --host 0.0.0.0 --port 8000
    ports:
      - "9001:8000"
    volumes:
      - .:/app
