name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Train tiny model
        run: python scripts/train_ai.py
      - name: Run tests
        run: pytest -q
      - name: Build Rust client
        run: |
          cd native/dragonshield_rust
          cargo build --release
